In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
# Seed number
np.random.seed(42)

In [4]:
# Create 150 instances of attributes for soccer players
completed_pass = np.random.randint(20, 100, size=150)
distance_traveled = np.round(np.random.uniform(8.0, 14.0, size=150), 1)
shots_on_goal = np.random.randint(0, 6, size=150)
disarms = np.random.randint(0, 15, size=150)

In [5]:
# Positions divided equally of line players
positions_players = ['Striker'] * 50 + ['Midfielder'] * 50 + ['Defender'] * 50

In [6]:
np.random.shuffle(positions_players)

In [7]:
dataset_players = {
    'completed_pass': completed_pass,
    'distance_traveled': distance_traveled,
    'shots_on_goal': shots_on_goal,
    'disarms': disarms,
    'positions_players': positions_players
}

In [8]:
dataframe_soccer_players = pd.DataFrame(dataset_players)

In [9]:
# df.to_csv('/mnt/data/football_player_performance_150.csv', index=False)

In [10]:
dataframe_soccer_players

,completed_pass,distance_traveled,shots_on_goal,disarms,positions_players
0,71,9.9,1,14,Midfielder
1,34,8.7,1,13,Midfielder
2,91,10.1,2,1,Defender
3,80,13.4,1,12,Midfielder
4,40,9.6,0,2,Midfielder
...,...,...,...,...,...
145,47,9.9,2,3,Defender
146,63,13.1,3,3,Midfielder
147,49,8.8,4,5,Midfielder
148,81,12.3,4,11,Defender
149,94,11.3,3,14,Striker

In [11]:
# Checking type
type(dataframe_soccer_players)

pandas.core.frame.DataFrame

In [12]:
# Checking the types of each column in dataframe
dataframe_soccer_players.dtypes

completed_pass         int32
distance_traveled    float64
shots_on_goal          int32
disarms                int32
positions_players     object
dtype: object

In [13]:
dataframe_soccer_players.head()

   completed_pass  distance_traveled  shots_on_goal  disarms positions_players
0              71                9.9              1       14        Midfielder
1              34                8.7              1       13        Midfielder
2              91               10.1              2        1          Defender
3              80               13.4              1       12        Midfielder
4              40                9.6              0        2        Midfielder

In [14]:
# Showing last lines
dataframe_soccer_players.tail()

,completed_pass,distance_traveled,shots_on_goal,disarms,positions_players
145,47,9.9,2,3,Defender
146,63,13.1,3,3,Midfielder
147,49,8.8,4,5,Midfielder
148,81,12.3,4,11,Defender
149,94,11.3,3,14,Striker

In [15]:
# Showing first ten lines
dataframe_soccer_players.head(10)

   completed_pass  distance_traveled  shots_on_goal  disarms positions_players
0              71                9.9              1       14        Midfielder
1              34                8.7              1       13        Midfielder
2              91               10.1              2        1          Defender
3              80               13.4              1       12        Midfielder
4              40                9.6              0        2        Midfielder
5              94               11.9              4        1        Midfielder
6              94                8.0              3        2          Defender
7              43               10.1              1        6          Defender
8              22                9.8              0        0           Striker
9              41                9.0              3        9        Midfielder

In [16]:
# Showing number of columns
dataframe_soccer_players.columns

Index(['completed_pass', 'distance_traveled', 'shots_on_goal', 'disarms',
       'positions_players'],
      dtype='object')

In [17]:
# Showing dimensions of dataset
dataframe_soccer_players.shape

(150, 5)

In [18]:
# Displaying the number of rows per column
dataframe_soccer_players.count()

completed_pass       150
distance_traveled    150
shots_on_goal        150
disarms              150
positions_players    150
dtype: int64

In [19]:
# Showing a statistical summary
dataframe_soccer_players.describe()

       completed_pass  distance_traveled  shots_on_goal     disarms
count      150.000000         150.000000     150.000000  150.000000
mean        58.400000          11.090667       2.573333    6.860000
std         23.750097           1.670604       1.676312    4.230014
min         20.000000           8.000000       0.000000    0.000000
25%         37.000000           9.700000       1.000000    3.000000
50%         60.000000          11.000000       3.000000    7.000000
75%         79.000000          12.375000       4.000000   10.750000
max         99.000000          14.000000       5.000000   14.000000

In [20]:
# Displaying information about columns and memory usage
dataframe_soccer_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   completed_pass     150 non-null    int32
 1   distance_traveled  150 non-null    float64
 2   shots_on_goal      150 non-null    int32
 3   disarms            150 non-null    int32
 4   positions_players  150 non-null    object
dtypes: float64(1), int32(3), object(1)
memory usage: 4.2+ KB

In [21]:
dataframe_soccer_players.sort_values(by='positions_players')

,completed_pass,distance_traveled,shots_on_goal,disarms,positions_players
34,83,10.7,5,9,Defender
31,81,11.8,3,12,Defender
90,82,9.8,0,4,Defender
137,47,13.1,2,0,Defender
36,70,11.6,3,8,Defender
...,...,...,...,...,...
73,97,13.3,1,11,Striker
72,91,11.3,0,2,Striker
69,33,9.6,0,11,Striker
82,48,13.6,5,14,Striker
149,94,11.3,3,14,Striker

In [22]:
dataframe_soccer_players.sort_values(by='disarms', ascending=False)

,completed_pass,distance_traveled,shots_on_goal,disarms,positions_players
0,71,9.9,1,14,Midfielder
78,43,13.1,4,14,Striker
141,81,12.0,2,14,Defender
111,84,10.1,1,14,Striker
102,31,11.3,1,14,Defender
...,...,...,...,...,...
59,25,13.0,3,0,Defender
58,21,11.1,2,0,Defender
50,63,10.0,3,0,Striker
117,33,11.4,1,0,Striker
43,79,10.4,4,0,Defender

In [23]:
dataframe_soccer_players['distance_traveled']

0       9.9
1       8.7
2      10.1
3      13.4
4       9.6
       ...
145     9.9
146    13.1
147     8.8
148    12.3
149    11.3
Name: distance_traveled, Length: 150, dtype: float64

In [24]:
# Selecting a subset of consecutive lines
dataframe_soccer_players[7:11]

,completed_pass,distance_traveled,shots_on_goal,disarms,positions_players
7,43,10.1,1,6,Defender
8,22,9.8,0,0,Striker
9,41,9.0,3,9,Midfielder
10,72,11.2,4,7,Defender

In [25]:
# Selecting a subset of columns of all lines
dataframe_soccer_players.loc[:, ['completed_pass', 'distance_traveled', 'shots_on_goal']]

     completed_pass  distance_traveled  shots_on_goal
0                71                9.9              1
1                34                8.7              1
2                91               10.1              2
3                80               13.4              1
4                40                9.6              0
..              ...                ...            ...
145              47                9.9              2
146              63               13.1              3
147              49                8.8              4
148              81               12.3              4
149              94               11.3              3

[150 rows x 3 columns]

In [26]:
# Selecting a subset of lines and columns
dataframe_soccer_players.loc[7:11, ['completed_pass', 'distance_traveled', 'shots_on_goal']]

    completed_pass  distance_traveled  shots_on_goal
7               43               10.1              1
8               22                9.8              0
9               41                9.0              3
10              72               11.2              4
11              21               10.9              3

In [27]:
# Selecting lines according to a criterion
dataframe_soccer_players[dataframe_soccer_players['completed_pass'] > 60]

,completed_pass,distance_traveled,shots_on_goal,disarms,positions_players
0,71,9.9,1,14,Midfielder
2,91,10.1,2,1,Defender
3,80,13.4,1,12,Midfielder
5,94,11.9,4,1,Midfielder
6,94,8.0,3,2,Defender
...,...,...,...,...,...
141,81,12.0,2,14,Defender
142,76,10.2,0,6,Defender
146,63,13.1,3,3,Midfielder
148,81,12.3,4,11,Defender
149,94,11.3,3,14,Striker

In [28]:
# Displaying the average for each attribute, groupying for position
dataframe_soccer_players.groupby('positions_players').mean()

                   completed_pass  distance_traveled  shots_on_goal  disarms
positions_players
Defender                    55.72             11.050           2.50     6.68
Midfielder                  56.12             11.046           2.82     6.70
Striker                     63.36             11.176           2.40     7.20

In [29]:
# Adding names for create an environment more realistic
name_striker = [
    'Cristiano Ronaldo', 'Lionel Messi', 'Neymar', 'Kylian Mbappé', 'Harry Kane',
    'Robert Lewandowski', 'Karim Benzema', 'Erling Haaland', 'Luis Suárez', 'Sergio Agüero',
    'Zlatan Ibrahimović', 'Eden Hazard', 'Paulo Dybala', 'Romelu Lukaku', 'Raheem Sterling',
    'Antoine Griezmann', 'Sadio Mané', 'Mohamed Salah', 'Pierre-Emerick Aubameyang', 'Ciro Immobile',
    'Timo Werner', 'Mauro Icardi', 'Gareth Bale', 'Gabriel Jesus', 'Edinson Cavani',
    'Lorenzo Insigne', 'Marcus Rashford', 'Jamie Vardy', 'Alexis Sánchez', 'Dusan Vlahovic',
    'Memphis Depay', 'Philippe Coutinho', 'João Félix', 'Lautaro Martínez', 'Ferran Torres',
    'Gonzalo Higuaín', 'Richarlison', 'Olivier Giroud', 'Riyad Mahrez', 'Angel Di Maria',
    'João Pedro', 'Pedro', 'Ángel Correa', 'Anthony Martial', 'Rodrygo',
    'Vinícius Júnior', 'Federico Chiesa', 'Iñaki Williams', 'Carlos Vela', 'André Silva'
]

name_Midfielder = [
    'Luka Modrić', 'Kevin De Bruyne', 'Paul Pogba', 'Toni Kroos', 'Sergio Busquets',
    'N\'Golo Kanté', 'Thiago Alcântara', 'Bruno Fernandes', 'David Silva', 'Marco Verratti',
    'James Rodríguez', 'Jordan Henderson', 'Frenkie de Jong', 'Joshua Kimmich', 'Christian Eriksen',
    'Mesut Özil', 'Thomas Müller', 'Casemiro', 'Rodri', 'Arturo Vidal',
    'Leon Goretzka', 'Saúl Ñíguez', 'Federico Valverde', 'Hakim Ziyech', 'Ivan Rakitić',
    'Phil Foden', 'Isco', 'Miralem Pjanić', 'Donny van de Beek', 'Dele Alli',
    'Adrien Rabiot', 'Sergej Milinković-Savić', 'Mason Mount', 'Jorginho', 'Andrés Iniesta',
    'Fabinho', 'Kai Havertz', 'Ilkay Gündogan', 'Denis Suárez', 'Arthur Melo',
    'Matteo Guendouzi', 'Lucas Torreira', 'Eduardo Camavinga', 'Weston McKennie', 'Houssem Aouar',
    'Franck Kessié', 'João Moutinho', 'Aaron Ramsey', 'Giovani Lo Celso', 'Declan Rice'
]

name_defender = [
    'Virgil van Dijk', 'Sergio Ramos', 'Gerard Piqué', 'Kalidou Koulibaly', 'Raphaël Varane',
    'Thiago Silva', 'Aymeric Laporte', 'Marquinhos', 'David Alaba', 'Leonardo Bonucci',
    'Giorgio Chiellini', 'Harry Maguire', 'Matthijs de Ligt', 'John Stones', 'Clement Lenglet',
    'Diego Godín', 'Stefan de Vrij', 'Ben Chilwell', 'Marcelo', 'Jordi Alba',
    'Trent Alexander-Arnold', 'Andrew Robertson', 'Achraf Hakimi', 'Dani Carvajal', 'Kyle Walker',
    'Lucas Hernández', 'Benjamin Pavard', 'Kieran Trippier', 'Juan Cuadrado', 'Victor Lindelöf',
    'Joe Gomez', 'Alex Telles', 'Nélson Semedo', 'Antonio Rüdiger', 'Eric García',
    'Alphonso Davies', 'Presnel Kimpembe', 'Fikayo Tomori', 'Pepe', 'Ezequiel Garay',
    'João Cancelo', 'Matteo Darmian', 'Niklas Süle', 'Serge Aurier', 'Lucas Digne',
    'David Luiz', 'Davinson Sánchez', 'Sokratis Papastathopoulos', 'Danilo', 'Matthias Ginter'
]

In [30]:
names_players_column = list()

In [31]:
# Adding names according your position
for position in dataframe_soccer_players['positions_players']:
    if position == 'Striker':
        names_players_column.append(name_striker.pop(0))
    elif position == 'Midfielder':
        names_players_column.append(name_Midfielder.pop(0))
    elif position == 'Defender':
        names_players_column.append(name_defender.pop(0))

In [32]:
names_players_column

['Luka Modrić',
 'Kevin De Bruyne',
 'Virgil van Dijk',
 'Paul Pogba',
 'Toni Kroos',
 'Sergio Busquets',
 'Sergio Ramos',
 'Gerard Piqué',
 'Cristiano Ronaldo',
 "N'Golo Kanté",
 'Kalidou Koulibaly',
 'Thiago Alcântara',
 'Lionel Messi',
 'Bruno Fernandes',
 'Raphaël Varane',
 'Thiago Silva',
 'Neymar',
 'Aymeric Laporte',
 'David Silva',
 'Marco Verratti',
 'Kylian Mbappé',
 'Marquinhos',
 'Harry Kane',
 'Robert Lewandowski',
 'Karim Benzema',
 'Erling Haaland',
 'Luis Suárez',
 'David Alaba',
 'Sergio Agüero',
 'Leonardo Bonucci',
 'Giorgio Chiellini',
 'Harry Maguire',
 'James Rodríguez',
 'Zlatan Ibrahimović',
 'Matthijs de Ligt',
 'Eden Hazard',
 'John Stones',
 'Jordan Henderson',
 'Frenkie de Jong',
 'Joshua Kimmich',
 'Clement Lenglet',
 'Diego Godín',
 'Christian Eriksen',
 'Stefan de Vrij',
 'Ben Chilwell',
 'Paulo Dybala',
 'Mesut Özil',
 'Thomas Müller',
 'Casemiro',
 'Rodri',
 'Romelu Lukaku',
 'Arturo Vidal',
 'Raheem Sterling',
 'Marcelo',
 'Antoine Griezmann',
 'Jordi Alba',
 'Leon Goretzka',
 'Sadio Mané',
 'Trent Alexander-Arnold',
 'Andrew Robertson',
 'Achraf Hakimi',
 'Saúl Ñíguez',
 'Federico Valverde',
 'Hakim Ziyech',
 'Mohamed Salah',
 'Pierre-Emerick Aubameyang',
 'Dani Carvajal',
 'Ciro Immobile',
 'Ivan Rakitić',
 'Timo Werner',
 'Kyle Walker',
 'Phil Foden',
 'Mauro Icardi',
 'Gareth Bale',
 'Gabriel Jesus',
 'Edinson Cavani',
 'Lorenzo Insigne',
 'Isco',
 'Marcus Rashford',
 'Miralem Pjanić',
 'Jamie Vardy',
 'Donny van de Beek',
 'Alexis Sánchez',
 'Dele Alli',
 'Dusan Vlahovic',
 'Adrien Rabiot',
 'Memphis Depay',
 'Sergej Milinković-Savić',
 'Lucas Hernández',
 'Mason Mount',
 'Benjamin Pavard',
 'Kieran Trippier',
 'Juan Cuadrado',
 'Philippe Coutinho',
 'João Félix',
 'Lautaro Martínez',
 'Jorginho',
 'Andrés Iniesta',
 'Victor Lindelöf',
 'Fabinho',
 'Kai Havertz',
 'Ferran Torres',
 'Joe Gomez',
 'Alex Telles',
 'Ilkay Gündogan',
 'Gonzalo Higuaín',
 'Richarlison',
 'Denis Suárez',
 'Nélson Semedo',
 'Olivier Giroud',
 'Riyad Mahrez',
 'Angel Di Maria',
 'João Pedro',
 'Antonio Rüdiger',
 'Eric García',
 'Pedro',
 'Arthur Melo',
 'Ángel Correa',
 'Alphonso Davies',
 'Matteo Guendouzi',
 'Anthony Martial',
 'Presnel Kimpembe',
 'Lucas Torreira',
 'Eduardo Camavinga',
 'Fikayo Tomori',
 'Weston McKennie',
 'Rodrygo',
 'Vinícius Júnior',
 'Pepe',
 'Federico Chiesa',
 'Ezequiel Garay',
 'João Cancelo',
 'Houssem Aouar',
 'Matteo Darmian',
 'Franck Kessié',
 'Niklas Süle',
 'Iñaki Williams',
 'Serge Aurier',
 'Lucas Digne',
 'João Moutinho',
 'Aaron Ramsey',
 'David Luiz',
 'Davinson Sánchez',
 'Sokratis Papastathopoulos',
 'Carlos Vela',
 'Danilo',
 'Giovani Lo Celso',
 'Declan Rice',
 'Matthias Ginter',
 'André Silva']

In [33]:
dataframe_soccer_players['name_player'] = names_players_column

In [34]:
dataframe_soccer_players

,completed_pass,distance_traveled,shots_on_goal,disarms,positions_players,name_player
0,71,9.9,1,14,Midfielder,Luka Modrić
1,34,8.7,1,13,Midfielder,Kevin De Bruyne
2,91,10.1,2,1,Defender,Virgil van Dijk
3,80,13.4,1,12,Midfielder,Paul Pogba
4,40,9.6,0,2,Midfielder,Toni Kroos
...,...,...,...,...,...,...
145,47,9.9,2,3,Defender,Danilo
146,63,13.1,3,3,Midfielder,Giovani Lo Celso
147,49,8.8,4,5,Midfielder,Declan Rice
148,81,12.3,4,11,Defender,Matthias Ginter
149,94,11.3,3,14,Striker,André Silva